package com.serb.ui;

import javax.swing.*;
import java.awt.*;

/**
 * User: SBezugliy
 * Date: 20.03.2009 17:39:29
 */
public class MainTest {
    private JTextArea testTextArea;
    private JPanel panel1;
    private JButton button1;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public void setData(TestBean data) {
    }

    public void getData(TestBean data) {
        button1.setText("dynamic");
    }

    public boolean isModified(TestBean data) {
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        testTextArea.setColumns(2);
        testTextArea.setText("Test");
        testTextArea.setToolTipText("Test tooltip");
        panel1.add(testTextArea, BorderLayout.NORTH);
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
